import { describe, it, expect } from "vitest";
import {
  isLockfilePath,
  isGeneratedPath,
  isLLMExcludedFile,
} from "./file-filters.js";

describe("isLockfilePath", () => {
  it.each([
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "bun.lock",
    "bun.lockb",
    "poetry.lock",
    "Pipfile.lock",
    "Cargo.lock",
    "Gemfile.lock",
    "go.sum",
    "composer.lock",
  ])("detects %s as lockfile", (file) => {
    expect(isLockfilePath(file)).toBe(true);
  });

  it("detects lockfiles in subdirectories", () => {
    expect(isLockfilePath("frontend/package-lock.json")).toBe(true);
    expect(isLockfilePath("services/api/yarn.lock")).toBe(true);
  });

  it("rejects non-lockfiles", () => {
    expect(isLockfilePath("package.json")).toBe(false);
    expect(isLockfilePath("src/lock.ts")).toBe(false);
    expect(isLockfilePath("go.mod")).toBe(false);
  });
});

describe("isGeneratedPath", () => {
  it.each([
    "dist/bundle.js",
    "build/output.css",
    "coverage/lcov.info",
    ".next/server/app.js",
    "vendor/autoload.php",
    "node_modules/foo/index.js",
  ])("detects %s as generated", (file) => {
    expect(isGeneratedPath(file)).toBe(true);
  });

  it.each([
    "app.min.js",
    "styles.min.css",
    "bundle.js.map",
    "main.bundle.js",
    "schema.generated.ts",
    "api.gen.go",
    "service.pb.go",
    "Form.designer.cs",
  ])("detects %s as generated by pattern", (file) => {
    expect(isGeneratedPath(file)).toBe(true);
  });

  it("rejects normal source files", () => {
    expect(isGeneratedPath("src/app.ts")).toBe(false);
    expect(isGeneratedPath("lib/utils.js")).toBe(false);
    expect(isGeneratedPath("README.md")).toBe(false);
  });
});

describe("isLLMExcludedFile", () => {
  it("excludes lockfiles", () => {
    expect(isLLMExcludedFile("package-lock.json")).toBe(true);
  });

  it("excludes generated files", () => {
    expect(isLLMExcludedFile("dist/bundle.js")).toBe(true);
  });

  it("includes normal source files", () => {
    expect(isLLMExcludedFile("src/index.ts")).toBe(false);
  });
});
