#!/usr/bin/env bun
/**
 * Generates src/llm/embedded-prompts.ts from the prompts/ directory.
 *
 * Bun's --compile flag bundles TypeScript but not .txt assets. By converting
 * prompts to a TypeScript map, they get compiled into the binary automatically.
 *
 * Run: bun scripts/embed-prompts.ts
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from "fs";
import { join, relative } from "path";

const ROOT = join(import.meta.dirname, "..");
const PROMPTS_DIR = join(ROOT, "prompts");
const OUTPUT = join(ROOT, "src/llm/embedded-prompts.ts");

function collectTxtFiles(dir: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      files.push(...collectTxtFiles(full));
    } else if (entry.endsWith(".txt")) {
      files.push(full);
    }
  }
  return files;
}

const files = collectTxtFiles(PROMPTS_DIR);

const entries = files.map((file) => {
  const key = relative(PROMPTS_DIR, file); // e.g. "review/review.v1.txt"
  const content = readFileSync(file, "utf-8");
  return { key, content };
});

const mapEntries = entries
  .map(({ key, content }) => {
    // Escape backticks and ${} in template literals
    const escaped = content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
    return `  ${JSON.stringify(key)}: \`${escaped}\``;
  })
  .join(",\n");

const source = `// AUTO-GENERATED by scripts/embed-prompts.ts — do not edit manually
// This file embeds prompt texts so they survive Bun's --compile bundling.

export const EMBEDDED_PROMPTS: Record<string, string> = {
${mapEntries},
};
`;

writeFileSync(OUTPUT, source, "utf-8");
console.log(`Embedded ${entries.length} prompt(s) → ${relative(ROOT, OUTPUT)}`);
